name: master
on:
  push:
    branches:
      - master
jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodeVersion: [ 20, 22, 24 ]
        jdkVersion: [ openjdk9, openjdk10, openjdk11, openjdk21 ]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodeVersion }}
      - name: npm ci
        run: npm ci
      - name: npm run format-cpp
        run: npm run format-cpp
      - name: npm run format
        run: npm run format
      - name: npm run lint
        run: npm run lint
      - name: Unit test
        run: npm test
